window.PORTFOLIO_DATA = {
  profile: {
    name: "阿晔",
    nameEn: "QURIOUS",
    legalName: "何晨晔",
    role: "AI 实践者 · 内容创作者",
    roleEn: "AI PRACTITIONER & CONTENT CREATOR",
    value: "I share how I use AI in real life—and turn complex tools into practical guides anyone can follow.",
    mottos: ["SLOW IS FAST.", "DONE IS BETTER THAN PERFECT.", "EVERYTHING HAS A PRICE."],
    wechatId: "_policeuncle",
    email: "quris525@163.com",
    photo: "assets/source/profile-home-master.jpg",
    photoAlt: "阿晔身穿白色西装的正面照片",
  },
  nav: [
    { id: "about", label: "认识我" },
    { id: "work", label: "代表作" },
    { id: "ai-hub", label: "AI 小站", href: "ai-hub.html" },
  ],
  socials: [
    {
      id: "x",
      name: "X",
      handle: "@aiqurious",
      metric: "672",
      metricLabel: "粉丝",
      href: "https://x.com/aiqurious",
      status: "LIVE",
      updatedAt: "2026.08.20",
      icon: "X",
    },
    {
      id: "xiaohongshu",
      name: "小红书",
      handle: "主页",
      metric: "—",
      metricLabel: "粉丝",
      href: "https://xhslink.cn/m/4jvEFZd0V1J",
      status: "SOON",
      updatedAt: "待补数据",
      icon: "小红书",
    },
    {
      id: "douyin",
      name: "抖音",
      handle: "22538930788",
      metric: "—",
      metricLabel: "粉丝",
      href: null,
      status: "SOON",
      updatedAt: "待补主页",
      icon: "♪",
    },
    {
      id: "bilibili",
      name: "哔哩哔哩",
      handle: "主页",
      metric: "1,128",
      metricLabel: "粉丝",
      href: "https://b23.tv/NOZUI11",
      status: "LIVE",
      updatedAt: "2026.08.20",
      icon: "B",
    },
    {
      id: "channels",
      name: "视频号",
      handle: "待补主页",
      metric: "—",
      metricLabel: "粉丝",
      href: null,
      status: "SOON",
      updatedAt: "待补链接",
      icon: "微",
    },
  ],
  stats: {
    total: "1,800",
    label: "已确认平台粉丝合计",
    updatedAt: "2026.08.20",
    note: "小红书、抖音、视频号数据待补；接入后台后可每日更新。",
  },
  featuredWork: {
    title: "AI 人生复刻短视频：零基础做出爆款「体验 100 种人生」的喂饭级教程",
    description: "一篇从零讲解如何用 AI 制作“体验 100 种人生”短视频的完整实操教程。",
    href: "https://x.com/aiqurious/status/2071213103505870899?s=20",
    cover: "assets/source/x-work-cover.jpg",
    coverAlt: "AI 人生复刻短视频代表作原封面",
    publishedAt: "2026.06.28",
    updatedAt: "2026.08.20",
    metrics: ["873 收藏", "555 喜欢", "108 转发"],
  },
  photography: [
    { src: "assets/photo-flowers.jpg", alt: "粉色花朵与蓝天的摄影作品" },
    { src: "assets/photo-autumn.jpg", alt: "秋叶与蓝天的摄影作品" },
    { src: "assets/photo-steps.jpg", alt: "两双鞋与路面心形图案的摄影作品" },
  ],
  tutorials: [
    {
      title: "Claude Code 保姆级教程（Mac）",
      meta: "飞书文档 · macOS",
      note: "从安装到第一次运行，按步骤完成配置。",
      href: "https://qcnhsga8t0cl.feishu.cn/wiki/KHJiwaLqdi5vZgkEHUxcqMgpnHd",
      type: "教程",
    },
    {
      title: "Claude Code 保姆级教程（Windows）",
      meta: "飞书文档 · Windows",
      note: "从零开始完成 Windows 安装和首次使用。",
      href: "https://qcnhsga8t0cl.feishu.cn/wiki/MkkTweQmzizQQQkgg4DcIMtknYb",
      type: "教程",
    },
    {
      title: "CC Switch 安装指南",
      meta: "站内说明 · 跨平台",
      note: "管理多种 AI 工具供应商配置的入门说明。",
      href: "https://github.com/farion1231/cc-switch/releases/latest",
      type: "教程",
    },
  ],
  resources: [
    {
      title: "CC Switch",
      meta: "跨平台 · 持续更新",
      note: "Claude Code、Codex 等 AI 工具的供应商切换管理器。",
      href: "https://github.com/farion1231/cc-switch/releases/latest",
      type: "资源",
    },
    {
      title: "storage-analyzer",
      meta: "Skills · 跨平台",
      note: "扫描磁盘占用并生成清理报告的技能。",
      href: null,
      type: "资源",
      status: "待补链接",
    },
    {
      title: "Codex 安装包",
      meta: "macOS / Windows",
      note: "安装文件整理完成后会在这里提供。",
      href: null,
      type: "资源",
      status: "待补文件",
    },
  ],
};
